### PR TITLE
Add `commit` info to the about panel

### PR DESCRIPTION
**Pull request by felipeg48**
@claudiahub @onobc 
Hi guys, I added the `commit` info to the about panel.

@claudiahub can you make sure I did the right thing? 
Also, I did add a link in the `src/app/about/info/info.component.html`

Don't know if that's a good way to doit.

This is related to this [PR](https://github.com/spring-cloud/spring-cloud-dataflow/pull/5541) as well.
We added some extra info to the `AboutController` on the server side.

### CODE REVIEW

**Comment by onobc** [comment]
Only marked as Draft to convey that it requires https://github.com/spring-cloud/spring-cloud-dataflow/pull/5547 prior to merging.

**Review by claudiahub — COMMENTED** [review]
@felipeg48 thanks Felipe, just wondering about the translations if it's intentional to keep the `Commit` text as it is spelled in English for all the three languages we have, correct ?
Other than that the code looks good to me. 
Thank you.

**Comment by felipeg48** [comment]
I'll do another commit to fix the new mode `simple` for the [PR-#5547](https://github.com/spring-cloud/spring-cloud-dataflow/pull/5547)

**Comment by felipeg48** [comment]
Done.. pending review. @onobc @claudiahub

**Review by claudiahub — APPROVED** [review]
Fixed a couple of minor linting issues.
Translations can be kept as they are since `Commit` is used here as a technical word.
Other than that, the overall PR looks good to me.

**Pull request merged**
