### PR TITLE
gh-743 Update Karma tests to include new browser versions

### PR DESCRIPTION
**Pull request by ghillert**
* Add `karma-firefox-launcher`
  - Adds the ability to run unit tests against Firefox using `ng test --browsers=Firefox`
* Add `karma-safari-launcher`
  - Adds the ability to run unit tests against Firefox using `ng test --browsers=Safari`
* Add `karma-edge-launcher`
  - Adds the ability (on Windows 10) to run unit tests against Edge using `ng test --browsers=Edge`

* Fix tests for Firefox
  - Adjust Flo unit tests for FF
* Fix tests for Edge
* Add SauceLabs Browser Targets for Karma unit tests
  - Chrome 67, Mac OS
  - Safari 11, Mac OS
  - Firefox 59, Mac OS
  - Edge 16, Windows 10
  - Chrome 67, Windows 10
  - Firefox 59, Windows 10
* Add BrowserStack Browser Targets for Karma unit tests
  - Chrome 65, Mac OS
  - Safari, Mac OS
  - Firefox 59, Mac OS
  - Edge 16, Windows 10
  - Chrome 67, Windows 10
  - Firefox 59, Windows 10
* Update Readme with BrowserStack + SauceLabs badges
* Minimize Logging for BrowserStack and Karma
  - Keep in mind 4MB logging maximum on Travis CI
  - Use dots reporter for Karma
  - Only log Warn+Error messages

Resolves spring-cloud/spring-cloud-dataflow-ui#743
Resolves spring-cloud/spring-cloud-dataflow-ui#872

### CODE REVIEW

**Comment by BoykoAlex** [comment]
@ghillert I have fix Flo unit tests on FF. Turns out Joint JS paper object needs to have some non 0 dimensions. I added a commit with a fix to this PR

**Comment by ilayaperumalg** [comment]
I keep getting this:

```
Safari 11.1.2 (Mac OS X 10.13.6): Executed 0 of 0 ERROR (0 secs / 0 secs)
16 08 2018 20:23:46.556:ERROR [reporter.browserlabs]: ✖ Test Errored
16 08 2018 20:31:52.020:WARN [Chrome 67.0.3396 (Mac OS X 10.13.6)]: Disconnected (1 times)
Chrome 67.0.3396 (Mac OS X 10.13.6) ERROR
  Disconnected
Chrome 67.0.3396 (Mac OS X 10.13.6) ERROR
  Disconnected
Chrome 67.0.3396 (Mac OS X 10.13.6): Executed 0 of 0 DISCONNECTED (7 mins 42.761 secs / 0 secs)
16 08 2018 20:31:52.021:ERROR [reporter.browserlabs]: ✖ Test Disconnected
```

and, it appears for other browsers different times.

**Comment by sabbyanandan** [comment]
@ghillert @ilayaperumalg: I was able to build the PR successfully. 

```
[INFO] LOG: 'Destroy [object Object],[object Object] task schedule(s).', [Object{name: 'foo1', taskName: 'bar1', status: 'complete', cronExpression: '0 0 0 * 8 1', _links       LOG: 'Destroy [object Object],[object Object] task schedule(s).', [Object{name: 'foo1', taskName: 'bar1', status: 'complete', cronExpression: '0 0 0 * 8 1', _links: Object{self: ...}}, Object{name: 'foo2', taskName: 'bar2', status: 'pending', cronExpression: '0 0 0 * 8 1', _links: Object{self: ...}}]
[INFO] HeadlessChrome 0.0.0 (Mac OS X 10.12.6): Executed 683 of 700 (skipped 9) SUCCESS (0 secs / 54.203 secs)
[INFO] LOG: 'Destroy [object Object],[object Object] task schedule(s).', [Object{name: 'foo1', taskName: 'bar1', status: 'complete', cronExpression: '0 0 0 * 8 1', _links: Object{self: ...}}, Object{name: 'foo2', taskName: 'bar2', status: 'pending', cronExpression: '0 0 0 * 8 1', _links: Object{self: ...}}]
[INFO] LOG: 'Destroy [object Object],[object Object] task schedule(s).', [Object{name: 'foo1', taskName: 'bar1', status: 'complete', cronExpression: '0 0 0 * 8 1', _links       HeadlessChrome 0.0.0 (Mac OS X 10.12.6): Executed 691 of 700 (skipped 9) SUCCESS (55.203 secs / 54.432 secs)
[INFO] TOTAL: 691 SUCCESS
[INFO] TOTAL: 691 SUCCESS
[INFO] TOTAL: 691 SUCCESS
[INFO] TOTAL: 691 SUCCESS
[INFO]
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ spring-cloud-dataflow-ui ---
[INFO] Building jar: /Users/sanandan/CodeSpaces/nextgen/forks/gunnar/spring-cloud-dataflow-ui/target/spring-cloud-dataflow-ui-1.7.0.BUILD-SNAPSHOT.jar
[INFO]
[INFO] --- maven-install-plugin:2.4:install (default-install) @ spring-cloud-dataflow-ui ---
[INFO] Installing /Users/sanandan/CodeSpaces/nextgen/forks/gunnar/spring-cloud-dataflow-ui/target/spring-cloud-dataflow-ui-1.7.0.BUILD-SNAPSHOT.jar to /Users/sanandan/.m2/repository/org/springframework/cloud/spring-cloud-dataflow-ui/1.7.0.BUILD-SNAPSHOT/spring-cloud-dataflow-ui-1.7.0.BUILD-SNAPSHOT.jar
[INFO] Installing /Users/sanandan/CodeSpaces/nextgen/forks/gunnar/spring-cloud-dataflow-ui/pom.xml to /Users/sanandan/.m2/repository/org/springframework/cloud/spring-cloud-dataflow-ui/1.7.0.BUILD-SNAPSHOT/spring-cloud-dataflow-ui-1.7.0.BUILD-SNAPSHOT.pom
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 04:51 min
[INFO] Finished at: 2018-08-17T10:58:50-07:00
[INFO] Final Memory: 17M/233M
[INFO] ------------------------------------------------------------------------
➜ spring-cloud-dataflow-ui ➤ 836507f|ghillert-gh-743✓
± mvn -U clean install
```

**Comment by ilayaperumalg** [comment]
@sabbyanandan The problem was with [running](https://github.com/spring-cloud/spring-cloud-dataflow-ui#running-tests---browserstack) the browser stack test, not the maven build:

```
npm run test-browserstack-local
```

**Comment by sabbyanandan** [comment]
Ah, sorry about that. Here's the local run results _(it took ~20mins to test on wifi)_:

```
➜ spring-cloud-dataflow-ui/ui ➤ 836507f|ghillert-gh-743✓
± npm run test-browserstack-local

...
...
.....
......
..............................................Chrome 67.0.3396 (Windows 10 0.0.0) WARN: 'BsDatepickerModule is under development,
      BREAKING CHANGES are possible,
      PLEASE, read changelog'

Chrome 67.0.3396 (Windows 10 0.0.0) WARN: 'BsDatepickerModule is under development,
      BREAKING CHANGES are possible,
      PLEASE, read changelog'
................................................
Chrome 67.0.3396 (Windows 10 0.0.0): Executed 691 of 700 (skipped 9) SUCCESS (2 mins 12.056 secs / 2 mins 11.624 secs)
TOTAL: 4146 SUCCESS
TOTAL: 4146 SUCCESS
```

**Comment by sabbyanandan** [comment]
I noticed a bunch of the following errors, but I'm not sure what they mean from the results perspective. The test run didn't interrupt or fail intermittently, though.

```
Chrome 67.0.3396 (Windows 10 0.0.0) ERROR: '          ^'
Chrome 67.0.3396 (Windows 10 0.0.0) ERROR: 'No whitespace allowed in destination'
Chrome 67.0.3396 (Windows 10 0.0.0) ERROR: 'No whitespace allowed in destination'
.Chrome 67.0.3396 (Windows 10 0.0.0) ERROR: '         ^'

Chrome 67.0.3396 (Windows 10 0.0.0) ERROR: '         ^'
Chrome 67.0.3396 (Windows 10 0.0.0) ERROR: 'Out of data - incomplete destination'
Chrome 67.0.3396 (Windows 10 0.0.0) ERROR: 'Out of data - incomplete destination'
.Chrome 67.0.3396 (Windows 10 0.0.0) ERROR: '      ^'

Chrome 67.0.3396 (Windows 10 0.0.0) ERROR: '      ^'
Chrome 67.0.3396 (Windows 10 0.0.0) ERROR: 'Out of data - incomplete destination'
Chrome 67.0.3396 (Windows 10 0.0.0) ERROR: 'Out of data - incomplete destination'
.Chrome 67.0.3396 (Windows 10 0.0.0) ERROR: ' ^'

Chrome 67.0.3396 (Windows 10 0.0.0) ERROR: ' ^'
Chrome 67.0.3396 (Windows 10 0.0.0) ERROR: 'No whitespace allowed in destination'
Chrome 67.0.3396 (Windows 10 0.0.0) ERROR: 'No whitespace allowed in destination'
..Chrome 67.0.3396 (Windows 10 0.0.0) ERROR: '      ^'

Chrome 67.0.3396 (Windows 10 0.0.0) ERROR: '      ^'
Chrome 67.0.3396 (Windows 10 0.0.0) ERROR: 'Out of data'
Chrome 67.0.3396 (Windows 10 0.0.0) ERROR: 'Out of data'
.Chrome 67.0.3396 (Windows 10 0.0.0) ERROR: '      ^'

Chrome 67.0.3396 (Windows 10 0.0.0) ERROR: '      ^'
Chrome 67.0.3396 (Windows 10 0.0.0) ERROR: 'No whitespace allowed after -- but before option name'
Chrome 67.0.3396 (Windows 10 0.0.0) ERROR: 'No whitespace allowed after -- but before option name'
.Chrome 67.0.3396 (Windows 10 0.0.0) ERROR: '         ^'

Chrome 67.0.3396 (Windows 10 0.0.0) ERROR: '         ^'
Chrome 67.0.3396 (Windows 10 0.0.0) ERROR: 'No whitespace allowed before equals'
Chrome 67.0.3396 (Windows 10 0.0.0) ERROR: 'No whitespace allowed before equals'
.Chrome 67.0.3396 (Windows 10 0.0.0) ERROR: '
```

**Comment by ghillert** [comment]
@sabbyanandan Those messages are currently normal error out put from Flo. I mentioned it early as part of https://github.com/spring-cloud/spring-cloud-dataflow-ui/issues/742

Probably low priority, but I created the following issue: https://github.com/spring-cloud/spring-cloud-dataflow-ui/issues/880

**Comment by ilayaperumalg** [comment]
Merging this now.

**Comment by ilayaperumalg** [comment]
Squashed and merged as 76f9228

**Pull request closed without merging**
