### PR TITLE
gh-165 Remove bulk-registration of apps from the UI

### PR DESCRIPTION
**Pull request by ghillert**
Resolves https://github.com/spring-cloud/spring-cloud-dataflow-ui/issues/165

### CODE REVIEW

**Comment by ilayaperumalg** [comment]
From #165 I assumed we wanted to remove the `bulk import` page itself. From the current changes on this PR, I see only the OOB app starters list for stream/task apps are removed from the `bulk import` page. @sabbyanandan @ghillert Could you clarify?

**Comment by ghillert** [comment]
@sabbyanandan Maybe you could just past your slack answer to my question here. Just double-checking that I have understood the requirements correctly.

**Comment by sabbyanandan** [comment]
@ilayaperumalg: The text-area is still applicable if someone wants to copy+paste app coordinates and register them that way. I don't see it confusing compared with how we had through bit.ly's previously. If there are any other concerns, it is fine to remove that as well.

**Comment by ilayaperumalg** [comment]
@sabbyanandan @ghillert I think it makes sense to keep the `bulk import` page at least if this wasn't reported as a confusion. LGTM, merging.

**Pull request merged**
