### PR TITLE
Fix for issue #836, splitting properties by new line and not by N

### LINKED ISSUE #836: Importing maven resourse, where the group id starts with "n"
Hi
If you try to use the bulk import apps, from properties, and your app maven identifier starts with n, the application does not get registered correctly.
For instance, trying to bulk import an application with the following descriptor will fail:
source.personSource=maven://net.sample:person-source:0.0.1-snapshot

I believe the bug can be fixed by changing:
https://github.com/spring-cloud/spring-cloud-dataflow-ui/blob/master/ui/src/app/apps/apps-bulk-import/properties/apps-bulk-import-properties.component.ts
line 91, to split by \n, and not by /n.

I think the intention was to break on new line, which this would accomplish.
thanks

### PR DESCRIPTION
**Pull request by kalvarez2**
This fixes #836.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@kalvarez2 Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-dataflow-ui&pullRequestId=860)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-cloud/spring-cloud-dataflow-ui&pullRequestId=860) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@kalvarez2 Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-dataflow-ui&pullRequestId=860)!

**Comment by kalvarez2** [comment]
It was literally one character change... glad I could help.

**Comment by oodamien** [comment]
Thanks @kalvarez2 for this fix.
Can you squash your 2 commits together before I merge it?

**Comment by kalvarez2** [comment]
@oodamien commits squashed in the fork. thanks

**Comment by oodamien** [comment]
@kalvarez2 4 commits are presents instead of 1

**Comment by kalvarez2** [comment]
okay, lets start over, let me fork again and create a new PR with one commit. feel free to close this one.

**Pull request closed without merging**
