### PR TITLE
gh-223 Add bulk-operations support for stream-list view

### LINKED ISSUE #223: Add bulk-operations support for stream-list view
As a developer, I'd like to add bulk-operations support in stream-lists view. 

**Acceptance:**

Following bulk operations are supported: 
- Deploy
- Undeploy
- Destroy

The bulk operation support is implemented for the App Registration page:

image

It uses the:

* `TriStateCheckboxComponent`
* `TriStateButtonComponent`

### PR DESCRIPTION
**Pull request by oodamien**
resolves #223 

Question: How do you want to handle this case when multiple stream definitions are selected to be deployed?

screen shot 2017-10-05 at 8 04 14 pm

Right now there is nothing to add deployment's properties.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@oodamien Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-dataflow-ui&pullRequestId=506)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-cloud/spring-cloud-dataflow-ui&pullRequestId=506) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@oodamien Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-dataflow-ui&pullRequestId=506)!

**Comment by sabbyanandan** [comment]
Hi, @oodamien. Thanks for the contribution! We haven't explored the user-experience for multi-stream deploys in the context of deployment properties. 

For bulk-deploy workflows, we could replace the "deployment properties" view with a list of streams on the left-pane as 🔘's and upon selection, the right-pane expands to accommodate the current deployment-properties view. The idea is that you're individually interacting with each stream and _optionally_ setting properties for each one of them. There can be other solutions, too.

**Comment by oodamien** [comment]
hi @sabbyanandan,

I implemented this UI/UX:
image

On "Add/edit deployment properties", it displays the following form:

image

Let me known if this behaviour is ok.

**Comment by ghillert** [comment]
Created https://github.com/spring-cloud/spring-cloud-dataflow-ui/issues/515 as a follow-up issue.

**Comment by ghillert** [comment]
Did some polishing but it looked good overall!! Thank you so much for the PR @oodamien. Great stuff!

Merged with commit 2435946226053ce19ed4753c7b4f3120267220f6

**Pull request closed without merging**
