### PR TITLE
Label component: fix text positioning

### LINKED ISSUE #935: Revisit label + text positioning in all the list pages

### PR DESCRIPTION
**Pull request by oodamien**
Resolves #935

### CODE REVIEW

**Comment by jvalkeal** [comment]
@oodamien Looks like this is just fixing .label to have same style as is .label-appty. Thus it really doesn't cause any visible changes. I'm not sure if @sabbyanandan meant to center text vertically as label seem to be slightly above center. At least I didn't see any changes when tried this.

**Comment by jvalkeal** [comment]
Tried padding `.45em .85em .3em` which might look better, but then I suck at css.
label-padding

**Comment by oodamien** [comment]
@jvalkeal 

Tried padding `.45em .85em .3em` but have this result:

image

**Comment by jvalkeal** [comment]
Lets look this tomorrow. Probably padding is not an answer as font representation is most like little different in every different system. Heh, I'll take screenshot tomorrow from windows browsers.

**Comment by oodamien** [comment]
System font and embedded font have a different render.

**Comment by jvalkeal** [comment]
Yeah and this font have relatively high upper and lower sides which makes it hard to center in a small space.

**Comment by jvalkeal** [comment]
I think I'm fine with you tweaks, merging.

**Comment by jvalkeal** [comment]
Merged per a02f1677608bceec300fd48d2baca5103a6430ad

**Pull request closed without merging**
