### PR TITLE
Stream deploy: force platform selection if more than 2 platforms

### LINKED ISSUE #1087: Force platform selection when >1 option is available for stream deployments
As a user, when deploying a stream with 4 platform-backends, I'm not forced to make a selection. Instead, the deployment picked the first platform from the list, and that is not the platform I wanted to deploy.

We would have to replicate what we did in Tasks via spring-cloud/spring-cloud-dataflow-ui#1075, but for streams.

### PR DESCRIPTION
**Pull request by oodamien**
Resolves #1087

### CODE REVIEW

**Comment by ilayaperumalg** [comment]
@oodamien The platform drop-down list has an item named `invalid` which can be removed
image

**Comment by oodamien** [comment]
@ilayaperumalg Thanks, I amended my last commit.

**Comment by ilayaperumalg** [comment]
LGTM, merging.

**Comment by ilayaperumalg** [comment]
Rebased and merged as 96751ce8

**Pull request closed without merging**
