### PR TITLE
Adjust for metadata not under attrs

### LINKED ISSUE #1488: DSL is not generated when creating task definitions using Flo
* Using the master branch on you local machine.
* Using the UI create a task definition by dragging the timestamp app from the selection list to the working area.
* Connect the timestamp app to the start and end icons properly.  
* Once that is complete, the DSL does not appear in the text box above.

### PR DESCRIPTION
**Pull request by BoykoAlex**
Fixes #1488 for master

### CODE REVIEW

**Comment by cppwfs** [comment]
There is no dialog that appears when I select the gear icon on the connector.    I can click the delete icon and it works.

**Comment by BoykoAlex** [comment]
I'll check why it's not showing up probably something that requires a fix similar what I've submitted in this PR...

**Comment by BoykoAlex** [comment]
@cppwfs The handler for **Options** click is commented out in master... The **master** branch had **ngx-bootstrap** dependency removed and hence the modal dialog support now comes from Clarity and was adopted in most places... This spot has been missed and would need be addressed in a separate issue scope.

**Comment by cppwfs** [comment]
LGTM

**Pull request merged**
