### PR TITLE
Off page rendering for fitLabel(...) function implementation

### PR DESCRIPTION
**Pull request by BoykoAlex**
A lot of white space changes due to IntelliJ `Code Format` - think it's good actually.
`fitLabel(...)` function is reworked to measure `tspan` size created off page with the same styling that is present on the actual page. Speeds up palette rendering by 20-25% (instead of updating and measuring text continuously on the page)

### CODE REVIEW

**Comment by sabbyanandan** [comment]
@ghillert: Please have a look when you get a chance.

**Comment by ghillert** [comment]
@BoykoAlex There is a lint error:

`render.service.ts[133, 15]: Shadowed variable: 'textView'`

**Comment by ghillert** [comment]
@BoykoAlex Not a deal maker for now - But do you think we could maybe chop this class into smaller pieces? Almost a 1000 lines of code is pushing it a bit IMO. Could you maybe create a follow-up issue?

**Comment by BoykoAlex** [comment]
@ghillert Fixed lint erro and factored out two helper classes from `Renderer` class.

**Comment by ghillert** [comment]
Merged with commit d1f6c620c83f03ec6fcdc74bc85c1afe09ab8621

**Pull request closed without merging**
