### PR TITLE
gh-379 Fix: Can access secure pages via URL

### PR DESCRIPTION
**Pull request by ghillert**
resolves https://github.com/spring-cloud/spring-cloud-dataflow-ui/issues/379

### CODE REVIEW

**Comment by cppwfs** [comment]
During testing, I could still could get in jobs and analytics via the URL .

**Comment by ghillert** [comment]
Rebased and made sure `AuthGuard` is provided to all top-level routes

**Comment by cppwfs** [comment]
LGTM

**Comment by cppwfs** [comment]
Found an issue where the data on the Job Execution page does not show up.
LGTM

**Comment by cppwfs** [comment]
LGTM

**Comment by cppwfs** [comment]
Squashed, Rebased, Merged.

**Pull request closed without merging**
