### PR TITLE
Syntax validation only for tasks without app name/properties verification

### PR DESCRIPTION
**Pull request by BoykoAlex**
- Support for turning on/off semantic validation of app and their options
- UI should have button "Verify Apps" added on the bulk define tasks page
- Unit tests for the option for the validator

### CODE REVIEW

**Comment by ilayaperumalg** [comment]
Given we only do DSL syntax verification when `verifyApps` is **not** invoked, can we specify the validation result to say *only* about `syntax` instead of saying `valid task definition detected`?

**Comment by BoykoAlex** [comment]
Yes. Changed to `syntactically correct` when `verifyApps` flag is off

**Comment by ilayaperumalg** [comment]
LGTM, merging.

**Comment by ilayaperumalg** [comment]
Squashed and merged as 7ffcc28c5c176ec5947fec407741e91913390273

**Pull request closed without merging**
