### PR TITLE
Remove unused websocket code

### LINKED ISSUE #258: About page starts non-working requests
Requests to `http://localhost:4200/websocket/info` start when visiting about page which result `404`. There requests doesn't stop even if navigating away from about page.

ui-about-bug

### PR DESCRIPTION
**Pull request by jvalkeal**
- Clean AboutComponent and remove websocket/stomp
  stuff which resulted runtime errors
- Fixes #258

### CODE REVIEW

**Comment by ilayaperumalg** [comment]
@jvalkeal It looks like we also need to remove the websocket related code from `about-detail` component and the `shared` module that has a `STOMP` service.

**Comment by jvalkeal** [comment]
@ilayaperumalg right ok, didn't realise there's that stuff in other places as well. I'll poke around again.

**Comment by jvalkeal** [comment]
@ilayaperumalg ok, removed websocket stuff from those extra modules.

**Comment by ilayaperumalg** [comment]
@jvalkeal Looks good and we need to remove the `STOMP` service and `sockjs` from `package.json`; I can do it while merging.

**Comment by ilayaperumalg** [comment]
Rebased and merged as 482fd2d9e20141eba94e221ee47ca070316d0faa along with 2296836b08dbebbfb3eee109e6d81f71072d7ab6

**Pull request closed without merging**
