### PR TITLE
Add platforms support for schedules

### LINKED ISSUE #1433: UI: Support platform selection for schedules
When more than platform is available a user must select a platform when 
- [ ] Creating a schedule
- [ ] Deleting a schedule
- [ ] Listing schedules
- [ ] Obtain a list of platforms that have schedules enabled via the 
```
    "tasks/platforms/scheduler": {
      "href": "http://localhost:9393/tasks/platforms/scheduler"
    },
```
Depends on https://github.com/spring-cloud/spring-cloud-dataflow/issues/3975

More can be read here: https://docs.google.com/document/d/17G302I3Z-w_74umJDmTf9IiXV3jgu5LKwMyIt-wjAK0/edit#

### PR DESCRIPTION
**Pull request by oodamien**
Resolves #1433

### CODE REVIEW

**Comment by cppwfs** [comment]
When creating a schedule an error occurs:
1. Go to task definition page
2. On the drop down select `Schedule Task`

The UI is attempting this call: `http://localhost:4200/tasks/schedules` , however the server returns this error message 
```
[{"logref":"IllegalArgumentException","message":"Must select a platform.  A default could not be determined because more than one platform had an associated scheduler"}]
``` 
In cases where there is more than one platform a user must select the platform when requesting schedules.

**Comment by cppwfs** [comment]
Also seeing same error when going to the schedules list page.

**Comment by jvalkeal** [comment]
It's weird that when I used server locally and just added `foo` and `bar` platforms for cf, I don't see these errors.

**Comment by cppwfs** [comment]
Hmm...   is scheduler enabled for both platforms?

**Comment by jvalkeal** [comment]
Does it check presence of a scheduler before trying to use those? It would make sense to target from local to cf but I was expecting some error to get thrown.

**Comment by cppwfs** [comment]
Dataflow checks to see if a task platform TaskLauncher has a scheduler associated with it.  If the tasklauncher has a scheduler associated with it, dataflow adds that to the pool of available schedulers.    If more than one tasklauncher has a scheduler then, dataflow will throw that exception.

**Comment by cppwfs** [comment]
I kicked the tires on the PR against the latest SCDF and it looks good.

**Pull request merged**
