### PR TITLE
IE 11, Edge, old browser versions don't support Array#findIndex()

### PR DESCRIPTION
**Pull request by BoykoAlex**
Resolves https://github.com/spring-cloud/spring-cloud-dataflow-ui/issues/75
Should also resolve the same issue for Chrome version <45

There are other UI glitches on IE11 and Edge... Tooltips aren't removed under some conditions... Zooming slider is ugly... This is just for the dialog to close because it's a real blocker

### CODE REVIEW

**Comment by markpollack** [comment]
I took this one since I have the browser in question that demonstrated this issue.

**Comment by markpollack** [comment]
This PR did not solve the problem for me.  It also raised the question of determining which UI build I was using.  The 'about' tab shows the server version but not the UI version - that would help make sure it wasn't a build error.  I built the UI locally via `mvn clean package install` and then a local build of the dataflow project.

**Comment by markpollack** [comment]
realized the pom for dataflow was pulling in 1.0 RC1 of the ui...retesting.

**Comment by ilayaperumalg** [comment]
Yeah, we haven't switched back to `SNAPSHOT` for the UI after RC1.

**Comment by markpollack** [comment]
Verified it works on chrome 43.0.2357.132 (64-bit) linux

**Pull request closed without merging**
