### PR TITLE
Stream Deploy/Update: wording

### LINKED ISSUE #1050: Reword stream-create to stream-update for when updating an existing stream
As a developer, I'd like to reword all the stream-create references to stream-update for when updating an existing stream.

Following items need correction:
- Rephrase `Deploy Stream` to `Update Stream` in the dropdown
- Rephrase `Deploy Stream` button to `Update Stream` in the stream-update page
- Reword the stream-update title to reflect the update operation
- Update any success/error messages if applicable
- Revise unit-test assertions if applicable

### PR DESCRIPTION
**Pull request by oodamien**
Updated wording on Stream Deploy Page
Resolves #1050

### CODE REVIEW

**Comment by ilayaperumalg** [comment]
Do we need to update the references at the page that is opened after clicking `Update Stream`? Currently, it shows as `Deploy`

**Comment by sabbyanandan** [comment]
@ilayaperumalg: Yeah, you're correct. I have listed three different places in the issue-description [see: https://github.com/spring-cloud/spring-cloud-dataflow-ui/issues/1050].

@oodamien: Could you reword the and push that text-change directly?

**Comment by ilayaperumalg** [comment]
LGTM, merging.

**Comment by ilayaperumalg** [comment]
Rebased and merged as c677025f

**Pull request closed without merging**
