### PR TITLE
Fix Lint errors

### LINKED ISSUE #1264: Fix Lint errors

### PR DESCRIPTION
**Pull request by oodamien**
Resolves #1264

### CODE REVIEW

**Comment by ilayaperumalg** [comment]
@sabbyanandan I don't think we need a new release for fixing the lint errors. Do you mean to do the release for any other bug fixes?

**Comment by sabbyanandan** [comment]
@ilayaperumalg: Please check the code changes. There are missing `;` and other things, which will break the page rendering.

**Comment by ilayaperumalg** [comment]
Cherry-picked into 2.2.x as 27d24a9e

**Comment by ilayaperumalg** [comment]
ok, Thanks @sabbyanandan.

Learned from @oodamien about the Grafana dashboard issue which happens to be part of the lint fixes.

The changes are in master as well as 2.2.x now.

**Pull request merged**
