### PR TITLE
Various Flo stream and composed tasks fixes

### LINKED ISSUE #511: Create Streams Tab - Palette not populated
Steps to reproduce:

1. Start a fresh SCDF Server (No apps visible yet)
2. `http://localhost:4200/#/streams/create` --> Palette is empty
3. `http://localhost:4200/#/apps` --> List is empty
4. Bulk Import apps: `http://bit.ly/Bacon-RELEASE-stream-applications-rabbit-maven
5. `http://localhost:4200/#/apps` --> Apps are being listed
6. `http://localhost:4200/#/streams/create` --> List is still empty

You have to do a full browser-refresh to get the list of apps.

### LINKED ISSUE #512: `Create Stream` button is enabled for a split-second when entering first letter
When creating a new stream under `http://localhost:4200/#/streams/create`:

I have an empty text-area and I start to type the first letter, then the Create Stream button is enabled for a split-second.

image

From @BoykoAlex:

The issue is validation kicks in after a debounce timeout time interval after user stops typing. There is no ideal fix for this. I see 2 options:

Make that timeout shorter (if CodeMirror leaves anything for the value to be customized)
Disable the button until validation is finished (for this I'd need to know when contents became invalid - an observer from Flo). This will make validation button flicker while graph/text being edited.

Related to: https://github.com/spring-cloud/spring-cloud-dataflow-ui/issues/450

### LINKED ISSUE #518: In Flo Editor - Add Loading Spinner when loading the Create Stream page
Add a loading spinner to `http://localhost:4200/#/streams/create`

E.g. It looks like the app-palette is loaded asynchronously, while the input fields are already enabled. We should have some loading indicator on the page and only allow input fields to be enabled, once the page is fully ready.

### LINKED ISSUE #519: [Composed Task] Grid button doesn't work
As a user, while using the composed-task canvas, I notice that the "Grid" button is dysfunctional.

### LINKED ISSUE #520: [Composed Task] Breaking a connection between the nodes invalidates the DSL
As a user, I tried to delete the connection between the nodes, which in turn invalidated the textual DSL.

**dsl:**
> timestamp && spark-yarn && <fpp || mytaskapp>

Delete the connection between `spark-yarn` and `mytaskapp`.

**changed dsl:**
> timestamp && spark-yarn && fpp

### LINKED ISSUE #521: [Composed Task] Graph disappears when there are invalid nodes in the DSL
As a user, I'm creating the following graph; instead of DSL failing with validation errors, the graph and textual-dsl content disappears entirely. 

**dsl:**
> timestamp && timestamp

Also, this behavior repeats for a valid DSL for the first few attempts.

### PR DESCRIPTION
**Pull request by BoykoAlex**
Fixes #521 
Fixes #520 
Fixes #519 
Fixes #511 
Fixes #512 
Fixes #518 

Some palette performance issues are addressed in core Flo, Flo version updated

Removed CA from composed tasks DSL editor because the CA is meant for `Bulk Define Tasks` UI feature for the task DSL.

### CODE REVIEW

**Comment by jvalkeal** [comment]
There's 6 failures in tests
```
StreamCreateComponent should be created
StreamCreateComponent disable stream creation for empty streams
StreamCreateComponent enable stream creation for valid stream
StreamCreateComponent disable stream creation for parse error
StreamCreateComponent disable stream creation for graph validation error marker
TaskCreateComposedTaskComponent should be created
```
Also some lint errors
```
$ ng lint
Warning: The 'no-use-before-declare' rule requires type checking

ERROR: /home/jvalkealahti/repos/spring/spring-cloud-dataflow-ui/ui/src/app/streams/stream-create/stream-create.component.ts[2, 24]: Too many spaces after 'from'
ERROR: /home/jvalkealahti/repos/spring/spring-cloud-dataflow-ui/ui/src/app/streams/stream-create/stream-create.component.ts[89, 9]: Missing semicolon
```

**Comment by jvalkeal** [comment]
ah, hold on, it did change flo version which I didn't update.

**Comment by jvalkeal** [comment]
Wiping and installing `node_modules` now gives different error for tests.
```
ERROR in Metadata version mismatch for module /home/jvalkealahti/repos/spring/spring-cloud-dataflow-ui/ui/node_modules/ngx-pagination/dist/ngx-pagination.d.ts, found version 4, expected 3, resolving symbol SharedModule in /home/jvalkealahti/repos/spring/spring-cloud-dataflow-ui/ui/src/app/shared/shared.module.ts, resolving symbol SharedModule in /home/jvalkealahti/repos/spring/spring-cloud-dataflow-ui/ui/src/app/shared/shared.module.ts
```
This same error also appear with `npm start`.

**Comment by BoykoAlex** [comment]
@jvalkeal I have fixed unit tests and lint issues. The `metadata error` during the build is something unrelated, I think you'll get it with master branch too if you wipe out `node_modules`

**Comment by BoykoAlex** [comment]
@jvalkeal Just confirmed that there is the same build error with master branch :-(

**Comment by jvalkeal** [comment]
Yeah, I see that as well with master. That's weird because I thought I had latest one from previous time when flo version got updated. Apparently I didn't.

**Comment by jvalkeal** [comment]
Looks like graph to dsl now adds END node to dsl which is not happening with old code.
flo-tasks-3

**Comment by jvalkeal** [comment]
Other fixes in this PR seems to work good.

**Comment by jvalkeal** [comment]
ok, above nitpick seem to be server issue. merging...

**Comment by jvalkeal** [comment]
squash/merge per https://github.com/spring-cloud/spring-cloud-dataflow-ui/commit/4be21fd6829a708fc3a32d37cdc9e9676c3e29f6

**Pull request closed without merging**
