### PR TITLE
Fix setting the value for property id vs name for Tasks

### LINKED ISSUE #569: Exit status of task is not reflected in graph DSL
_From @jvmlet on December 12, 2017 7:23_

Hello
I'm using the  latest 1.3.0_SNAPSHOT built and in below screenshot the transition from `1` to `2` is configured with exit status `COMPLETED` and from `1` to `3` with exit  status `FAILED`.
These configurations are not reflected in DSL.
 In `1.2.3.RELEASE` it was properly handled in generated graph DSL.
 
image

_Copied from original issue: spring-cloud/spring-cloud-dataflow#1832_

### PR DESCRIPTION
**Pull request by BoykoAlex**
Fixes spring-cloud/spring-cloud-dataflow-ui#569

### CODE REVIEW

**Comment by cppwfs** [comment]
Hmm, I'm rendering the image as shown and adding the exit status for `FAILED` and` COMPLETED` but still getting the same result i.e. 
1: AAA && <2: AAA || 3: AAA>
When I should be getting:
1: AAA 'FAILED'->2: AAA 'COMPLETED'->3: AAA

**Comment by BoykoAlex** [comment]
@cppwfs can you give it another try please?
I've pulled latest from master, merged with my fork master, rebased my branch `gh-569` on master. Ran the maven build of the UI, ran `npm start` and it worked ok for me... If I create the task just by building the graph as well as pasting the DSL.
screen shot 2017-12-20 at 18 03 26
screen shot 2017-12-20 at 18 03 57

**Comment by cppwfs** [comment]
@BoykoAlex I retested.  And you are correct.  My apologies.  
LGTM

**Comment by cppwfs** [comment]
Rebased, Merged.

**Pull request closed without merging**
