### PR TITLE
Stream deployment info popup

### LINKED ISSUE #572: Make the stream-list's status column a hyperlink for deployed streams
As a developer, I'd like to make the stream lists status column a hyperlink, so we can show a dialog-view of details returned from the `stream info` command/endpoint. 

Refer to spring-cloud/spring-cloud-dataflow#1848 for the background.

**Acceptance:**
- Apply this change only when SCDF is configured to be on Skipper-mode (i.e., spring.cloud.dataflow.features.skipper-enabled).
- Automatically render a hyperlink when the status is either "Deployed", "Deploying", or "Failed".
- Rename the "status" column to "info".
- Add "stream info" tool-tip to the hyperlink.
- When clicking the hyperlink, open a new dialog window to include the associated stream information returned via `stream info` command/endpoint.

### LINKED ISSUE #587: Read-only Flo graph fails to load
With the latest build from `master`, an undeployed ticktock stream failed with the following error. The read-only graph won't render either.

image

image

### PR DESCRIPTION
**Pull request by BoykoAlex**
Fixes #572 
Fixes #587 

Pop-over instead of the dialog.
Column remains to be `status` column
The pop-over content has minimum styling for now.
No tests added, but if it looks good I'll add some tests as well.

### CODE REVIEW

**Comment by sabbyanandan** [comment]
Also, given that we persist deployment properties for classic and skipper modes, we would want to enable the "stream info" component for both modes.

**Comment by BoykoAlex** [comment]
@sabbyanandan Updates PR for comments, added a few tests.

**Comment by ghillert** [comment]
@BoykoAlex Could you please fix the lint errors? `ng lint  --type-check`

**Comment by BoykoAlex** [comment]
@ghillert Fixed lint errors and squashed commits.

**Comment by ghillert** [comment]
still see 3 lint errors:

```
ERROR: /Users/hillert/dev/git/spring-cloud-dataflow-ui/ui/src/app/shared/flo/support/app-metadata.ts[39, 63]: variable 'AppPropertyMetadata' used before declaration
ERROR: /Users/hillert/dev/git/spring-cloud-dataflow-ui/ui/src/app/streams/stream-definitions/deployment-properties-info/deployment-properties-info.component.ts[51, 24]: variable 'KeyValuePair' used before declaration
ERROR: /Users/hillert/dev/git/spring-cloud-dataflow-ui/ui/src/app/streams/stream-definitions/deployment-properties-info/deployment-properties-info.component.ts[54, 16]: variable 'DeployedAppProperties' used before declaration
```

**Comment by BoykoAlex** [comment]
@ghillert fixed the remaining lint errors

**Pull request merged**
