### PR TITLE
Support unique stream name from the Flo UI

### PR DESCRIPTION
**Pull request by BoykoAlex**
Pivotal tracker story: https://www.pivotaltracker.com/story/show/117723927

### CODE REVIEW

**Comment by BoykoAlex** [comment]
Needs a bit of polishing and testing

**Comment by BoykoAlex** [comment]
PR ready for review. 
Duplicate stream are detected when editing stream-name on a an app on the canvas via the properties dialog. Checks whether stream-name is unique on the canvas and unique among stream definitions on the server.
Duplicate streams are detected when create stream button is pressed on the popped up create streams dialog. Checks whether there are any duplicates between stream names currently entered in the form. Checks whether stream name is unique among stream names on the server.
Some minor styling updates for the create stream dialog and properties dialog.

**Comment by aclement** [comment]
Seems to be a slight problem:
I have:
a=time|log
asdf=time|log

Then I press create stream. I change 'a' to asdf (causes dup message to appear) then to 'xxx'

And the dup message remains.

**Comment by aclement** [comment]
Alex fixed that up, re-tested. all working. Merging

**Pull request closed without merging**
