### PR TITLE
Stream Deployment Properties: fix parsing

### LINKED ISSUE #985: Stream deploy: popup deployment properties
The deployment properties are not displayed.

image

### PR DESCRIPTION
**Pull request by oodamien**
Resolves #985

### CODE REVIEW

**Comment by ilayaperumalg** [comment]
@oodamien Could you check the travis build failure? I restarted the build and it keeps failing.

**Comment by ilayaperumalg** [comment]
LGTM, merging.

**Comment by ilayaperumalg** [comment]
@oodamien It looks like the 1.7.x branch requires some additional changes as I don't see `fromJson` or `pageFromJSON` being used in `stream-definition.ts`

**Comment by oodamien** [comment]
@ilayaperumalg PR related to the 2.0.0 (no backport)

**Pull request closed without merging**
