### PR TITLE
gh-526 Update to Angular 5 (Incl CLI 1.5)

### PR DESCRIPTION
**Pull request by ghillert**
* Update versions to Angular `5.2.3` and Angular CLI `1.6.7`
* Compare and update all relevant files from a freshly created angular CLI project
* Fix issues around Angular2 Busy and RxJs
  - Use the latest GitHub version of Angular2 Busy
  - Polish RxJs imports
* Remove StompJS for (Not used and has issues with Angular 5)
* Update `ngx-bootstrap` to `2.0.0-beta.8` to fix build error
* Update `ngx-clipboard` from `8.1.3` to `9.0.0`
* Update `compodoc` from `1.0.3` to `1.0.4`
* Update `d3` from `4.11.0` to `4.12.0`
* Switch from `template` to `ng-template` to get tooltips working again
* Switch from PhantomJS to headless Chrome for test executions
* Ensure Maven build passes

resolves https://github.com/spring-cloud/spring-cloud-dataflow-ui/issues/526

### CODE REVIEW

**Comment by sabbyanandan** [comment]
@ghillert: It turns out Flo upgrade to Angular-5 is not as trivial as it is in SCDF's Dashboard. Given it involves a significant rework in Flo, I suggest that we drop it for now and pick it up post 1.3 GA release.

**Comment by BoykoAlex** [comment]
@ghillert looks like the build issue with Angular 5 migration is https://github.com/ReactiveX/rxjs/issues/3060 I have switched Flo to Angular 5, but can't test really because of this issue... (Flo angular 5 branch for SCSDF UI dependency https://github.com/spring-projects/spring-flo/tree/angular5)

**Comment by ghillert** [comment]
Hitting also this issue: https://github.com/angular/angular/issues/20415

**Comment by ghillert** [comment]
@BoykoAlex @sabbyanandan @cppwfs @jvalkeal The Angular5 upgrade should be good to go now. Please check it out :-)

**Comment by cppwfs** [comment]
Getting the following exception when viewing the Runtime Applications tab:
```
error-handler.ts:35 Cannot read property 'appInstanceStatusResourceList' of undefined
ErrorHandler.handleError @ error-handler.ts:35
CatchSubscriber.error @ catchError.js:105
MapSubscriber._next @ map.js:82
Subscriber.next @ Subscriber.js:91
onLoad @ http.js:1556
ZoneDelegate.invokeTask @ zone.js:425
onInvokeTask @ core.js:4620
ZoneDelegate.invokeTask @ zone.js:424
Zone.runTask @ zone.js:192
ZoneTask.invokeTask @ zone.js:499
invokeTask @ zone.js:1540
globalZoneAwareCallback @ zone.js:1566
XMLHttpRequest.send (async)
(anonymous) @ VM5438:1
scheduleTask @ zone.js:2933
ZoneDelegate.scheduleTask @ zone.js:411
onScheduleTask @ zone.js:301
ZoneDelegate.scheduleTask @ zone.js:405
Zone.scheduleTask @ zone.js:236
Zone.scheduleMacroTask @ zone.js:259
(anonymous) @ zone.js:2966
proto.(anonymous function) @ zone.js:1366
(anonymous) @ http.js:1605
Observable._trySubscribe @ Observable.js:172
Observable.subscribe @ Observable.js:160
MapOperator.call @ map.js:57
Observable.subscribe @ Observable.js:157
CatchOperator.call @ catchError.js:80
Observable.subscribe @ Observable.js:157
RuntimeAppsComponent.loadRuntimeApps @ runtime-apps.component.ts:39
RuntimeAppsComponent.ngOnInit @ runtime-apps.component.ts:35
checkAndUpdateDirectiveInline @ core.js:12095
checkAndUpdateNodeInline @ core.js:13598
checkAndUpdateNode @ core.js:13541
debugCheckAndUpdateNode @ core.js:14413
debugCheckDirectivesFn @ core.js:14354
(anonymous) @ RuntimeAppsComponent_Host.ngfactory.js? [sm]:1
debugUpdateDirectives @ core.js:14339
checkAndUpdateView @ core.js:13508
callViewAction @ core.js:13858
execEmbeddedViewsAction @ core.js:13816
checkAndUpdateView @ core.js:13509
callViewAction @ core.js:13858
execComponentViewsAction @ core.js:13790
checkAndUpdateView @ core.js:13514
callWithDebugContext @ core.js:14740
debugCheckAndUpdateView @ core.js:14277
ViewRef_.detectChanges @ core.js:11300
(anonymous) @ core.js:5786
ApplicationRef.tick @ core.js:5786
(anonymous) @ core.js:5619
ZoneDelegate.invoke @ zone.js:392
onInvoke @ core.js:4629
ZoneDelegate.invoke @ zone.js:391
Zone.run @ zone.js:142
NgZone.run @ core.js:4446
next @ core.js:5619
schedulerFn @ core.js:4223
SafeSubscriber.__tryOrUnsub @ Subscriber.js:239
SafeSubscriber.next @ Subscriber.js:186
Subscriber._next @ Subscriber.js:127
Subscriber.next @ Subscriber.js:91
Subject.next @ Subject.js:56
EventEmitter.emit @ core.js:4203
checkStable @ core.js:4594
onHasTask @ core.js:4642
ZoneDelegate.hasTask @ zone.js:445
ZoneDelegate._updateTaskCount @ zone.js:465
Zone._updateTaskCount @ zone.js:289
Zone.runTask @ zone.js:209
drainMicroTaskQueue @ zone.js:602
ZoneTask.invokeTask @ zone.js:503
invokeTask @ zone.js:1540
globalZoneAwareCallback @ zone.js:1566
XMLHttpRequest.send (async)
(anonymous) @ VM5438:1
scheduleTask @ zone.js:2933
ZoneDelegate.scheduleTask @ zone.js:411
onScheduleTask @ zone.js:301
ZoneDelegate.scheduleTask @ zone.js:405
Zone.scheduleTask @ zone.js:236
Zone.scheduleMacroTask @ zone.js:259
(anonymous) @ zone.js:2966
proto.(anonymous function) @ zone.js:1366
(anonymous) @ http.js:1605
Observable._trySubscribe @ Observable.js:172
Observable.subscribe @ Observable.js:160
MapOperator.call @ map.js:57
Observable.subscribe @ Observable.js:157
CatchOperator.call @ catchError.js:80
Observable.subscribe @ Observable.js:157
(anonymous) @ Observable.js:286
ZoneAwarePromise @ zone.js:890
Observable.toPromise @ Observable.js:284
(anonymous) @ app.module.ts:34
ApplicationInitStatus.runInitializers @ core.js:3451
(anonymous) @ core.js:5379
_callAndReportToErrorHandler @ core.js:5558
(anonymous) @ core.js:5377
ZoneDelegate.invoke @ zone.js:392
onInvoke @ core.js:4629
ZoneDelegate.invoke @ zone.js:391
Zone.run @ zone.js:142
NgZone.run @ core.js:4446
PlatformRef.bootstrapModuleFactory @ core.js:5368
(anonymous) @ core.js:5447
ZoneDelegate.invoke @ zone.js:392
Zone.run @ zone.js:142
(anonymous) @ zone.js:873
ZoneDelegate.invokeTask @ zone.js:425
Zone.runTask @ zone.js:192
drainMicroTaskQueue @ zone.js:602
Promise resolved (async)
scheduleMicroTask @ zone.js:585
ZoneDelegate.scheduleTask @ zone.js:414
Zone.scheduleTask @ zone.js:236
Zone.scheduleMicroTask @ zone.js:256
scheduleResolveOrReject @ zone.js:871
ZoneAwarePromise.then @ zone.js:981
PlatformRef.bootstrapModule @ core.js:5447
(anonymous) @ main.ts:11
../../../../../src/main.ts @ main.bundle.js:1747
__webpack_require__ @ inline.bundle.js:55
0 @ main.bundle.js:1769
__webpack_require__ @ inline.bundle.js:55
webpackJsonpCallback @ inline.bundle.js:26
(anonymous) @ main.bundle.js:1
core.js:1350 ERROR TypeError: __WEBPACK_IMPORTED_MODULE_0_rxjs_Observable__.a.throw is not a function
    at CatchSubscriber.ErrorHandler.handleError [as selector] (error-handler.ts:36)
    at CatchSubscriber.error (catchError.js:105)
    at MapSubscriber._next (map.js:82)
    at MapSubscriber.Subscriber.next (Subscriber.js:91)
    at XMLHttpRequest.onLoad (http.js:1556)
    at ZoneDelegate.invokeTask (zone.js:425)
    at Object.onInvokeTask (core.js:4620)
    at ZoneDelegate.invokeTask (zone.js:424)
    at Zone.runTask (zone.js:192)
    at ZoneTask.invokeTask [as invoke] (zone.js:499)
```
I was able to reproduce this by starting a stream and then going to the Runtime tab.

**Comment by ghillert** [comment]
Rebased and updated to Angular `5.2.3` and Angular CLI `1.6.7`.

**Comment by ghillert** [comment]
Created https://github.com/spring-cloud/spring-cloud-dataflow-ui/issues/614

**Comment by cppwfs** [comment]
LGTM....  All in agreement to merge?

**Comment by cppwfs** [comment]
Rebased Merged

**Pull request closed without merging**
