### PR TITLE
gh-7 Replace XD Logo with SCDF logo

### PR DESCRIPTION
**Pull request by ghillert**
* Replace main header logo
* Replace favicon
* Ensure icon works for IOS (Add to Home Screen)

Resolves spring-cloud/spring-cloud-dataflow-ui#7

### CODE REVIEW

**Comment by ilayaperumalg** [comment]
I think we can change the `name` of the logo image to refer `dataflow` instead of `xd`

**Comment by ghillert** [comment]
@ilayaperumalg Made the changes

**Comment by ilayaperumalg** [comment]
I get a build failure when running `mvm package install` :

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 06:15 min
[INFO] Finished at: 2016-03-21T19:41:48+05:30
[INFO] Final Memory: 9M/245M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:0.0.23:grunt (grunt build) on project spring-cloud-dataflow-ui: Failed to run task: 'grunt build --no-color' failed. (error code 3) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by ghillert** [comment]
Rebased.

**Comment by ilayaperumalg** [comment]
LGTM, merged as a0cffbbf8e4dea58dc3608e713a732d24d74f2d9

**Pull request closed without merging**
