### PR TITLE
gh-491 Analytics dashboard selectors don't restore

### PR DESCRIPTION
**Pull request by ghillert**
resolves https://github.com/spring-cloud/spring-cloud-dataflow-ui/issues/491

### CODE REVIEW

**Comment by cppwfs** [comment]
Found one issue.  If a user selects just a metric type(nothing else) and then clicks the job tab and then returns back to the analytics page, the page is `busy` and both the analytics and job components are showing.   The error displayed is as follows: 
```
ERROR TypeError: Cannot read property 'name' of undefined
    at AnalyticsService.webpackJsonp.../../../../../src/app/analytics/analytics.service.ts.AnalyticsService.startPollingForSingleDashboardItem (analytics.service.ts:305)
```

**Comment by ghillert** [comment]
@cppwfs 

- Rebased
- Improved error handling (generate toasty message in case Redis is not running for counters)
- Made additional check when starting the polling for a dashboard item (Ensure Counter is defined)

**Comment by cppwfs** [comment]
LGTM WOOT! WOOT!

**Comment by cppwfs** [comment]
Squashed Merged

**Pull request closed without merging**
