### PR TITLE
Fix some leftovers from dynamic base paths

### PR DESCRIPTION
**Pull request by klopfdreh**
Hey @jvalkeal - I just found some leftovers and also a not closed div tag in the logout-oauth-success.html

After I found those occurrences I did a full search for `href="/` but there are no others. I guess after this PR the change is finished.

### CODE REVIEW

**Comment by klopfdreh** [comment]
Belongs to https://github.com/spring-cloud/spring-cloud-dataflow-ui/issues/747

**Comment by klopfdreh** [comment]
I changed baseUrl to baseApiUrl, because otherwise the context-path is not used as it was: `/` compared to`<context-path>/` but with dashboard at the end which is wrong.

**Comment by jvalkeal** [comment]
Thx, I just started to do some more work around security so this comes at a good time!

**Comment by jvalkeal** [comment]
This was nice!. Merged per 2dc865cdfa50f973e8f68bd8bcb1fd02e64a4ee6

**Pull request closed without merging**
