### PR TITLE
Stream Deploy Edit

### LINKED ISSUE #625: Add edit link from the Flo-graph to update versions and properties
As a user, I'd like to edit the Flo-graph from the list page, so I can update the app versions and its properties.

**Acceptance:**
- Show "edit" link from read-only Flo graph
- Clicking the edit link would redirect to stream deployment page 
- User should be able to update version, deployer, and application properties

Note: This depends on spring-cloud/spring-cloud-dataflow-ui#515 (see [comment](https://github.com/spring-cloud/spring-cloud-dataflow-ui/issues/515#issuecomment-364801670)).

### PR DESCRIPTION
**Pull request by oodamien**
Resolves #625 

Issue:
Platform property is not saved on stream deploy.

### CODE REVIEW

**Comment by oodamien** [comment]
The stream is now undeploy if the status is `deployed` or `deploying` and then the stream is deploy.

**Comment by ghillert** [comment]
image

Add the `server.port` property:

image

I then end up with the wrong property:

image

Leading to:

image

If I then try to remove it:

image

It is not removed from the stream definition:

image

**Comment by oodamien** [comment]
This is the limitation: https://github.com/spring-cloud/spring-cloud-dataflow/issues/2184

**Comment by ghillert** [comment]
Reviewed - thx @oodamien  for the last code-review fix. Merged.

**Pull request merged**
